services:
  weather.api:
    image: weather.api
    build:
      context: .
      dockerfile: Weather.API/Dockerfile
    ports:
      - "8080:8080"
      
  redis:
    image: redis
    ports:
      - "6379:6379"
